input_name = 'Введите имя: '
input_surname = 'Введите фамилию: '
input_lastname = 'Введите отчество: '
input_telephone_number = 'Введите номер телефона: '
input_extra_data = 'Введите дополнительную информацию: '
result_to_add = 'Вы добавили новый контакт.'
result_to_delete = 'Вы удалили контакт.'
result_to_import_format1 = 'Вы импортировали  формат 1.'
result_to_import_format2 = 'Вы импортировали  формат 2.'
result_to_export_format1 = 'Вы экспортировали в формат 1. Файл появится после закрытия программы'
result_to_export_format2 = 'Вы экспортировали в формат 2. Файл появится после закрытия программы '
result_to_view = 'Ваши контакты :'
result_to_find_contact_surname = 'Контакт найден.'
result_to_exit = 'Справочник закрыт!'
no_result = 'Операцию не удалось осуществить.'
instarction_delete = "Введите фамилию или телефон. Если в базе есть однофамильцы, введите фамилию " \
              "и имя  \n в строку, иначе удалятся все контакты с такой фамилией "